# Write a complete CRD chart directory from sanitized CRDs + metadata.

use config.nu *
use templatize.nu *

const SCHEMA_HEADER = "# yaml-language-server: $schema=https://json.schemastore.org/chart.json"

# --- helpers ------------------------------------------------------------------

def storage-version [crd: record]: nothing -> record {
  let versions = ($crd.spec.versions | default [])
  let storage = ($versions | where {|v| ($v | get -o storage | default false) })
  if ($storage | is-empty) { $versions | last } else { $storage.0 }
}

def served-versions [crd: record]: nothing -> list<string> {
  $crd.spec.versions | where {|v| ($v | get -o served | default false) } | get name
}

# First sentence of the storage version's schema description, single line, bounded.
def crd-description [crd: record]: nothing -> string {
  let desc = (storage-version $crd | get -o schema.openAPIV3Schema.description | default "")
  let one_line = ($desc | str replace -ra '\s+' ' ' | str trim)
  let first = ($one_line | split row '. ' | get 0 | str trim)
  let bounded = (if ($first | str length) > 200 { ($first | str substring 0..197) + "..." } else { $first })
  if ($bounded | is-empty) { $"($crd.spec.names.kind) custom resource" } else { $bounded }
}

def uses-cel [crds: list<record>]: nothing -> bool {
  $crds | to json | str contains "x-kubernetes-validations"
}

export def "emit kube-version" [crds: list<record>]: nothing -> string {
  if (uses-cel $crds) { ">=1.25.0-0" } else { ">=1.16.0-0" }
}

def ah-crds-annotation [crds: list<record>]: nothing -> string {
  $crds
  | each {|c| {
      kind: $c.spec.names.kind
      version: (storage-version $c).name
      name: $c.metadata.name
      displayName: $c.spec.names.kind
      description: (crd-description $c)
    } }
  | to yaml
}

def source-paths [manifest: record]: nothing -> list<string> {
  $manifest.sources | each {|s|
    match $s.kind {
      "git-path" | "kustomize" => $s.path
      "helm-template" => $s.chartPath
      "release-asset" => $"release asset ($s.asset)"
    }
  }
}

def upstream-tree-url [manifest: record, tag: string, path: string]: nothing -> string {
  $"($manifest.upstream.repo)/tree/($tag)/($path)"
}

# --- Chart.yaml ----------------------------------------------------------------

# Chart.yaml as a record, WITHOUT version and artifacthub.io/changes (added by `emit chart-yaml`).
export def "emit chart-record" [
  manifest: record
  resolved: record
  crds: list<record>
  license: record
]: nothing -> record {
  let links = (
    [
      {name: "Upstream project", url: $manifest.upstream.homepage}
      {name: "Upstream repository", url: $manifest.upstream.repo}
    ]
    | append (source-paths $manifest | where {|p| not ($p | str starts-with "release asset") } | each {|p| {name: $"Upstream CRD source \(($p)\)", url: (upstream-tree-url $manifest $resolved.tag $p)} })
    | append [
      {name: "Chart source", url: $"($REPO_URL)/tree/main/charts/($manifest.name)"}
      {name: "Verify signature and attestations", url: $"($REPO_URL)#verifying-what-you-install"}
    ]
  )
  let annotations = {
    "artifacthub.io/license": $license.spdx
    "artifacthub.io/crds": (ah-crds-annotation $crds)
    "artifacthub.io/links": ($links | to yaml)
    $"($ANNOTATION_PREFIX)/upstream-repo": $manifest.upstream.repo
    $"($ANNOTATION_PREFIX)/upstream-tag": $resolved.tag
    $"($ANNOTATION_PREFIX)/upstream-commit": $resolved.sha
  }
  let base = {
    apiVersion: "v2"
    name: $manifest.name
    description: $manifest.description
    type: "application"
    appVersion: $resolved.appVersion
    kubeVersion: (emit kube-version $crds)
    home: $manifest.upstream.homepage
  }
  let with_icon = (if $manifest.upstream.icon == null { $base } else { $base | insert icon $manifest.upstream.icon })
  $with_icon
  | insert sources [$REPO_URL $manifest.upstream.repo]
  | insert keywords ["crds" ($manifest.name | str replace -r '-crds$' '')]
  | insert maintainers [{name: $OWNER, url: $"https://github.com/($OWNER)"}]
  | insert annotations $annotations
}

# Final Chart.yaml text: record + version + changes, keys in conventional order.
export def "emit chart-yaml" [chart_record: record, version: string, changes: list<string>]: nothing -> string {
  let ordered = (
    {apiVersion: $chart_record.apiVersion, name: $chart_record.name, description: $chart_record.description, type: $chart_record.type, version: $version, appVersion: $chart_record.appVersion}
    | merge ($chart_record | reject apiVersion name description type appVersion annotations)
    | insert annotations ($chart_record.annotations | insert "artifacthub.io/changes" ($changes | to yaml))
  )
  [
    $SCHEMA_HEADER
    "# GENERATED by tooling/crdgen from sources/<name>.yaml. Do not edit."
    ($ordered | to yaml)
  ] | str join "\n"
}

# --- values ---------------------------------------------------------------------

export def "emit values-yaml" []: nothing -> string {
  [
    "# GENERATED by tooling/crdgen. Do not edit."
    "# All CRD charts in this repository share exactly these values."
    ""
    "# -- Extra annotations added to every CRD."
    "annotations: {}"
    "# -- Extra labels added to every CRD."
    "labels: {}"
    "# -- Add `helm.sh/resource-policy: keep` so the CRDs (and therefore every custom"
    "# resource of these APIs) survive `helm uninstall`. Set to false only if you really"
    "# want `helm uninstall` to delete all of them."
    "keepOnUninstall: true"
    ""
  ] | str join "\n"
}

export def "emit values-schema" []: nothing -> string {
  {
    "$schema": "https://json-schema.org/draft-07/schema#"
    "$id": $"($REPO_URL)/values.schema.json"
    title: "CRD chart values"
    type: "object"
    additionalProperties: false
    properties: {
      annotations: {type: "object", additionalProperties: {type: "string"}, description: "Extra annotations added to every CRD."}
      labels: {type: "object", additionalProperties: {type: "string"}, description: "Extra labels added to every CRD."}
      keepOnUninstall: {type: "boolean", description: "Add helm.sh/resource-policy: keep so CRDs survive helm uninstall."}
    }
  } | to json --indent 2 | $"($in)\n"
}

export def "emit ci-values" []: nothing -> string {
  [
    "# Used by chart-testing (ct install) only: let ct clean up CRDs between charts"
    "# sharing a kind cluster. Not a recommended production setting."
    "keepOnUninstall: false"
    ""
  ] | str join "\n"
}

# --- NOTICE / README ----------------------------------------------------------

export def "emit notice" [manifest: record, resolved: record, license: record]: nothing -> string {
  let ours = [
    $"The CustomResourceDefinition manifests under templates/ were copied from"
    $"  ($manifest.upstream.repo)"
    $"at tag ($resolved.tag) \(commit ($resolved.sha)\), path\(s\): (source-paths $manifest | str join ', ')"
    $"and modified by ($REPO_URL): Helm labels, annotations and templating were"
    $"added; server-side metadata and upstream Helm release metadata were removed."
    $"Upstream license: ($license.spdx) \(see LICENSE in this directory\)."
    ""
  ]
  let upstream_notice = (if $license.notice_text == null { [] } else { [($license.notice_text | str trim) "" "----" ""] })
  $upstream_notice | append $ours | str join "\n"
}

def crd-table [crds: list<record>]: nothing -> list<string> {
  let rows = ($crds | each {|c|
    let storage = (storage-version $c).name
    let versions = ($c.spec.versions | each {|v|
      let served = ($v | get -o served | default false)
      let label = (if $v.name == $storage { $"**($v.name)**" } else { $v.name })
      if $served { $label } else { $"~~($label)~~" }
    } | str join ", ")
    $"| `($c.metadata.name)` | ($c.spec.names.kind) | ($c.spec.group) | ($c.spec.scope) | ($versions) |"
  })
  [
    "| CRD | Kind | Group | Scope | Versions |"
    "|-----|------|-------|-------|----------|"
  ] | append $rows
}

export def "emit readme" [
  manifest: record
  resolved: record
  crds: list<record>
  dropped: list<string>
  license: record
  --oversized # projected release above SIZE_BUDGET_CAP (see `validate size-budget`)
]: nothing -> string {
  let name = $manifest.name
  let oci = $"($OCI_BASE)/($name)"
  let crd_names = ($crds | get metadata.name | str join " ")
  let paths = (source-paths $manifest)
  let conflicts = ($manifest.conflictsWith | each {|c| $"`($c)`" } | str join ", ")
  let dropped_section = (if ($dropped | is-empty) { [] } else {
    [
      "## Not included"
      ""
      "Upstream ships these alongside the CRDs; this chart intentionally contains"
      "CustomResourceDefinitions only:"
      ""
    ] | append ($dropped | each {|d| $"- `($d)`" }) | append [""]
  })
  let conflicts_section = (if ($manifest.conflictsWith | is-empty) { [] } else {
    [
      $"> **Warning:** this chart defines the same CRD names as ($conflicts). Install only one of them on a cluster."
      ""
    ]
  })
  let release = ($name | str replace -r '-crds$' '')
  let install_commands = (if not $oversized {
    [
      "```sh"
      $"helm install ($release) ($oci) --version <version>"
      "```"
      ""
    ]
  } else {
    [
      "> **Too large for Helm's default storage.** Helm stores each release in one Secret"
      "> \(or ConfigMap\), capped at 1 MiB; this chart's release exceeds it. Use the SQL"
      "> storage driver \(PostgreSQL\):"
      ""
      "```sh"
      "export HELM_DRIVER=sql"
      "export HELM_DRIVER_SQL_CONNECTION_STRING='postgresql://<user>:<password>@<host>:5432/<db>'"
      $"helm upgrade --install ($release) ($oci) --version <version> --history-max=1"
      "```"
      ""
    ]
  })
  [
    $"# ($name)"
    ""
    "<!-- GENERATED by tooling/crdgen. Do not edit. -->"
    ""
    $"($manifest.description)."
    ""
    $"CRDs are copied verbatim from [($manifest.upstream.repo | str replace 'https://github.com/' '')]\(($manifest.upstream.repo)\)"
    $"at tag [`($resolved.tag)`]\(($manifest.upstream.repo)/tree/($resolved.tag)\) \(commit `($resolved.sha)`\),"
    $"path\(s\) ($paths | each {|p| $'`($p)`' } | str join ', '), and rendered as regular Helm templates so that"
    "`helm upgrade` updates them \(Helm's own `crds/` directory never upgrades\)."
    ""
  ]
  | append $conflicts_section
  | append [
    "## Install"
    ""
  ]
  | append $install_commands
  | append [
    "Chart `version` equals the upstream version it ships; `appVersion` is always the exact upstream version."
    $"Installing requires Kubernetes (emit kube-version $crds | str replace '-0' '')."
    ""
    "### Already have these CRDs?"
    ""
    "If the CRDs were installed by the operator chart or `kubectl apply`, Helm refuses with"
    "\"rendered manifests contain a resource that already exists\". Either let Helm adopt them:"
    ""
    "```sh"
    $"helm install ($release) ($oci) --version <version> --take-ownership   # Helm >= 3.17"
    "```"
    ""
    "or, on older Helm, hand them over first \(replace `<release>` and `<namespace>`\):"
    ""
    "```sh"
    $"kubectl annotate crd ($crd_names) \\"
    "  meta.helm.sh/release-name=<release> meta.helm.sh/release-namespace=<namespace> --overwrite"
    $"kubectl label crd ($crd_names) \\"
    "  app.kubernetes.io/managed-by=Helm --overwrite"
    "```"
    ""
    "## Values"
    ""
    "| Key | Type | Default | Description |"
    "|-----|------|---------|-------------|"
    "| `annotations` | object | `{}` | Extra annotations added to every CRD. |"
    "| `labels` | object | `{}` | Extra labels added to every CRD. |"
    "| `keepOnUninstall` | bool | `true` | Add `helm.sh/resource-policy: keep` so CRDs \(and all their custom resources\) survive `helm uninstall`. |"
    ""
    "Unknown keys are rejected \(`values.schema.json`\)."
    ""
    "## CRDs"
    ""
  ]
  | append (crd-table $crds)
  | append [
    ""
    "Bold = storage version, ~~struck~~ = not served."
    ""
  ]
  | append $dropped_section
  | append [
    "## Verify"
    ""
    "```sh"
    $"REF=($OCI_HOST_PATH)/($name):<version>"
    "cosign verify \\"
    $"  --certificate-identity-regexp '($COSIGN_IDENTITY_REGEXP)' \\"
    $"  --certificate-oidc-issuer ($COSIGN_OIDC_ISSUER) \\"
    "  $REF"
    "cosign verify-attestation --type spdxjson \\"
    $"  --certificate-identity-regexp '($COSIGN_IDENTITY_REGEXP)' \\"
    $"  --certificate-oidc-issuer ($COSIGN_OIDC_ISSUER) \\"
    "  $REF"
    $"gh attestation verify oci://$REF --owner ($OWNER)"
    "```"
    ""
    "## License and attribution"
    ""
    $"The CRD manifests are the work of the ($manifest.upstream.repo | str replace 'https://github.com/' '') project,"
    $"licensed under ($license.spdx) \(copy in [`LICENSE`]\(./LICENSE\), modification statement in [`NOTICE`]\(./NOTICE\)\)."
    $"Chart scaffolding is Apache-2.0, \u{00a9} ($OWNER). Generated by [spnngl/charts]\(($REPO_URL)\);"
    "updates are automated, please report problems there rather than upstream."
    ""
  ]
  | str join "\n"
}

# --- orchestration ---------------------------------------------------------------

# Write everything except Chart.yaml into `dir` (which is created empty).
export def "emit chart-files" [
  dir: path
  manifest: record
  resolved: record
  crds: list<record>
  dropped: list<string>
  license: record
]: nothing -> nothing {
  if ($dir | path exists) { rm -rf $dir }
  mkdir ($dir | path join "templates") ($dir | path join "ci")
  for c in $crds {
    templatize crd $c $manifest.name | save -f ($dir | path join "templates" $"($c.metadata.name).yaml")
  }
  templatize helpers $manifest.name | save -f ($dir | path join "templates" "_helpers.tpl")
  emit values-yaml | save -f ($dir | path join "values.yaml")
  emit values-schema | save -f ($dir | path join "values.schema.json")
  emit ci-values | save -f ($dir | path join "ci" "ci-values.yaml")
  $license.license_text | save -f ($dir | path join "LICENSE")
  emit notice $manifest $resolved $license | save -f ($dir | path join "NOTICE")
  emit readme $manifest $resolved $crds $dropped $license | save -f ($dir | path join "README.md")
  emit helmignore | save -f ($dir | path join ".helmignore")
}

# Standard `helm create` patterns plus `ci/`: ct reads ci/*-values.yaml from the
# chart directory, the packaged chart (and therefore the release) does not need it.
export def "emit helmignore" []: nothing -> string {
  [
    "# Patterns to ignore when building packages."
    "# This supports shell glob matching, relative path matching, and"
    "# negation \(prefixed with !\). Only one pattern per line."
    "# This file is only needed to package; keep it out of the release."
    ".helmignore"
    ".DS_Store"
    "Thumbs.db"
    "# Common VCS dirs"
    ".git/"
    ".gitignore"
    ".bzr/"
    ".bzrignore"
    ".hg/"
    ".hgignore"
    ".svn/"
    "# Common backup files"
    "*.swp"
    "*.bak"
    "*.tmp"
    "*~"
    "# Various IDEs"
    ".project"
    ".idea/"
    "*.tmproj"
    "# Ignore local testing values or charts"
    "*.local.*"
    "*.tgz"
    "# helm/charts"
    "OWNERS"
    "hack/"
    "ci/"
    ""
    "unittests/"
    "files/dashboards/"
    ""
    "UPGRADE.md"
    "CONTRIBUTING.md"
    ".editorconfig"
    ""
  ] | str join "\n"
}
