{{- if .Values.metrics.serviceMonitor.enabled }}
{{- $m := .Values.metrics.serviceMonitor }}
{{- $endpoint := dict "path" "/metrics" "port" "metrics" }}
{{- with $m.interval }}{{ $_ := set $endpoint "interval" . }}{{ end }}
{{- with $m.scrapeTimeout }}{{ $_ := set $endpoint "scrapeTimeout" . }}{{ end }}
{{- with $m.relabelings }}{{ $_ := set $endpoint "relabelings" . }}{{ end }}
{{- with $m.metricRelabelings }}{{ $_ := set $endpoint "metricRelabelings" . }}{{ end }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- toYaml (merge (include "cloudflared.labels" . | fromYaml) (deepCopy $m.labels)) | nindent 4 }}
  name: {{ include "cloudflared.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
    {{- toYaml (list $endpoint) | nindent 4 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "cloudflared.selectorLabels" . | nindent 6 }}
{{- end }}
